# Basic Settings
id: "apex-minion-01"
location: "Apex"
http-url: "http://opennms1:8980/opennms"

# Inter Process Communication
ipc:
  rpc:
    kafka:
      bootstrap.servers: "kafka1:9092"
      single-topic: "true"
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="opennms" password="0p3nNM5";
  sink:
    kafka:
      bootstrap.servers: "kafka1:9092"
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="opennms" password="0p3nNM5";

# Trap/Syslog Reception
netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514
  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162

# Flows
telemetry:
  flows:
    listeners:
      Netflow-Listener:
        class-name: "org.opennms.netmgt.telemetry.listeners.UdpListener"
        parameters:
          port: 8877
        parsers:
          Netflow-9:
            class-name: "org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow9UdpParser"
            queue:
              use-routing-key: "true"
            parameters:
              dnsLookupsEnabled: "false"
          Netflow-5:
            class-name: "org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser"
            queue:
              use-routing-key: "true"
            parameters:
              dnsLookupsEnabled: "false"
